// dashboard.jsx — main dashboard layout wiring all sections together

const { useState: useS } = React;

// Apply the parsed offer fields onto the shared OFFER object (in place).
function applyParsedOffer(parsed) {
  Object.assign(OFFER, {
    company:    parsed.company    ?? OFFER.company,
    role:       parsed.role       ?? OFFER.role,
    location:   parsed.location   ?? OFFER.location,
    base:       parsed.baseSalary ?? OFFER.base,
    signOn:     parsed.signOnBonus ?? OFFER.signOn,
    rsuTotal:   parsed.rsuTotal   ?? OFFER.rsuTotal,
    rsuYears:   parsed.rsuVestingYears ?? OFFER.rsuYears,
    bonusPct:   parsed.annualBonusPercent ?? OFFER.bonusPct,
    companyTag: "",
  });
}

// ── AIBadge — uncertainty label shown on every Claude-generated section ──────
function AIBadge({ label = "AI estimate" }) {
  return (
    <span className="ai-badge" title="Generated by AI from public knowledge — verify before relying on it.">
      <span className="ai-badge-dot" aria-hidden="true" />
      {label}
    </span>
  );
}

// Extract PDF text in the browser via pdf.js (loaded on demand).
async function extractPdfText(file) {
  const pdfjsLib = await loadPdfJs();
  const buf = await file.arrayBuffer();
  const pdf = await pdfjsLib.getDocument({ data: buf }).promise;
  let text = "";
  for (let i = 1; i <= pdf.numPages; i++) {
    const page = await pdf.getPage(i);
    const content = await page.getTextContent();
    text += content.items.map((it) => it.str).join(" ") + "\n";
  }
  return text.trim();
}

function OfferInput({ onDecoded, label = "Paste your offer letter here", cta = "Decode" }) {
  const [text, setText] = useS("");
  const [loading, setLoading] = useS(false);
  const [stage, setStage] = useS(null); // "parsing" | "brief"
  const [error, setError] = useS(null);
  const [fileName, setFileName] = useS(null);

  const decode = async (offerText) => {
    if (!offerText.trim() || loading) return;
    setLoading(true);
    setError(null);
    try {
      setStage("parsing");
      const response = await fetch("/api/parse-offer", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ offerText }),
      });
      const payload = await response.json();
      if (!response.ok) throw new Error(payload.error || "Failed to parse offer");
      applyParsedOffer(payload.offer);

      // Second call: company/location context brief (slower — it's a Claude call).
      setStage("brief");
      try {
        const briefRes = await fetch("/api/offer-brief", {
          method: "POST",
          headers: { "content-type": "application/json" },
          body: JSON.stringify({ offer: OFFER }),
        });
        const briefPayload = await briefRes.json();
        if (briefRes.ok && briefPayload.brief) applyBrief(briefPayload.brief);
      } catch (briefErr) {
        // Brief is best-effort — numeric sections still render with defaults.
        console.warn("offer-brief failed:", briefErr);
      }

      recomputeY1();
      onDecoded();
    } catch (e) {
      setError(e && e.message ? e.message : String(e));
    } finally {
      setLoading(false);
      setStage(null);
    }
  };

  const handleFile = async (e) => {
    const file = e.target.files && e.target.files[0];
    if (!file) return;
    setFileName(file.name);
    setError(null);
    try {
      if (file.type === "application/pdf" || file.name.toLowerCase().endsWith(".pdf")) {
        setLoading(true);
        setStage("parsing");
        const extracted = await extractPdfText(file);
        setText(extracted);
        setLoading(false);
        setStage(null);
        if (extracted) decode(extracted);
      } else {
        const raw = await file.text();
        setText(raw);
        if (raw) decode(raw);
      }
    } catch (err) {
      setLoading(false);
      setStage(null);
      setError("Couldn't read that file: " + (err && err.message ? err.message : String(err)));
    }
  };

  const stageLabel = stage === "brief" ? "Researching company & location…" : "Reading your offer…";

  return (
    <section className="offer-input">
      <label className="offer-input-label" htmlFor="offer-text">
        {label}
      </label>
      <textarea
        id="offer-text"
        className="offer-input-textarea"
        value={text}
        onChange={(e) => setText(e.target.value)}
        placeholder="Paste the full text of your offer letter, or upload a PDF below…"
        rows={6}
        disabled={loading}
      />
      <div className="offer-input-row">
        <button
          className="offer-input-btn"
          onClick={() => decode(text)}
          disabled={loading || !text.trim()}
        >
          {loading ? (
            <>
              <span className="offer-input-spinner" aria-hidden="true" />
              {stageLabel}
            </>
          ) : (
            cta
          )}
        </button>
        <label className="offer-input-upload">
          <input type="file" accept="application/pdf,.pdf,.txt" onChange={handleFile} disabled={loading} hidden />
          <span>⬆ Upload PDF</span>
        </label>
        {fileName && !loading && <span className="offer-input-file">{fileName}</span>}
        {error && <div className="offer-input-error">⚠ {error}</div>}
      </div>
    </section>
  );
}

function WelcomeBanner({ onClose }) {
  return (
    <div className="welcome-banner" role="region" aria-label="Welcome message">
      <div className="welcome-inner">
        <div className="welcome-icon" aria-hidden="true">
          <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" strokeWidth="2"
               strokeLinecap="round" strokeLinejoin="round">
            <path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"/>
          </svg>
        </div>
        <div className="welcome-copy">
          <strong>First time decoding an offer? You&rsquo;re in the right place.</strong>
          <span className="welcome-sub">Underlined terms have plain-English definitions on hover. Toggle <em>Learn mode</em> to see them inline.</span>
        </div>
        <button className="welcome-close" onClick={onClose} aria-label="Dismiss welcome message">✕</button>
      </div>
    </div>
  );
}

function Header({ learn, onLearn }) {
  const [logoErr, setLogoErr] = useS(false);
  const domain = BRIEF.companyDomain;
  const companyName = (OFFER.company && OFFER.company.name) || OFFER.company;

  // Reset error state if the company changes (e.g. after re-parsing a new offer).
  React.useEffect(() => { setLogoErr(false); }, [domain]);

  const showFallback = logoErr || !domain;

  return (
    <header className="site-hd">
      <div className="site-hd-inner">
        <div style={{ display: "flex", alignItems: "center", gap: 12, minWidth: 0 }}>
          {showFallback ? (
            // lucide-react Briefcase fallback — used when the Clearbit logo 404s
            // or the company has no domain yet.
            <svg
              viewBox="0 0 24 24"
              width="48"
              height="48"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
              aria-hidden="true"
              style={{ flexShrink: 0, color: "var(--ink-60)" }}
            >
              <rect width="20" height="14" x="2" y="7" rx="2" ry="2" />
              <path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
            </svg>
          ) : (
            <img
              src={`https://logo.clearbit.com/${domain}`}
              alt={`${companyName} logo`}
              height="48"
              onError={() => setLogoErr(true)}
              style={{
                height: 48,
                width: "auto",
                display: "block",
                flexShrink: 0,
                borderRadius: 8,
                objectFit: "contain",
              }}
            />
          )}
          <span
            style={{
              fontWeight: 600,
              fontSize: 18,
              color: "var(--ink)",
              whiteSpace: "nowrap",
              overflow: "hidden",
              textOverflow: "ellipsis",
            }}
          >
            {companyName}
          </span>
        </div>
        <div className="site-hd-title">Your offer, decoded</div>
        <div className="site-hd-actions">
          <button className={"learn-toggle" + (learn ? " on" : "")}
                  onClick={() => onLearn(!learn)}
                  title="Show plain-English definitions inline">
            <span className="learn-toggle-dot" aria-hidden="true">{learn ? "✓" : "i"}</span>
            Learn mode
          </button>
          <div className="site-hd-badge" title="Built for first-gen students navigating their first tech offer">
            <span className="dot" /> First-gen friendly
          </div>
        </div>
      </div>
    </header>
  );
}

function MetaStrip() {
  const mark = (OFFER.company || "?").trim().charAt(0).toUpperCase();
  const tag = BRIEF.ticker ? "NYSE/Nasdaq: " + BRIEF.ticker : (BRIEF.isPublic === false ? "Private" : null);
  return (
    <div className="meta-strip">
      <div className="meta-strip-row">
        <div className="meta-co">
          <div className="meta-co-mark" aria-hidden="true">{mark}</div>
          <div>
            <div className="meta-co-name">{OFFER.company}{tag && <span className="meta-co-tag"> · {tag}</span>}</div>
            <div className="meta-co-sub">{OFFER.role} &nbsp;·&nbsp; {OFFER.location}</div>
          </div>
        </div>
        <div className="meta-parsed">
          <span className="meta-parsed-check" aria-hidden="true">✓</span>
          <span>Offer letter parsed · just now</span>
        </div>
      </div>
    </div>
  );
}

function Headline() {
  const says = OFFER.base + OFFER.signOn + OFFER.rsuTotal / OFFER.rsuYears + OFFER.base * OFFER.bonusPct;
  const cityName = (BRIEF.location && BRIEF.location.city) || locationCity(OFFER.location);
  const stateCode = (BRIEF.location && BRIEF.location.state) || "";
  const taxPct = Math.round((Y1.combinedTax || 0) * 1000) / 10;
  const stateRate = BRIEF.location ? num(BRIEF.location.stateEffectiveRate, 0) : 0;
  return (
    <section className="headline">
      <div className="headline-eyebrow">Estimated first-year take-home, after taxes &amp; {cityName} rent <AIBadge /></div>
      <div className="headline-number">
        <CountUp value={Y1.takeHome} />
      </div>
      <div className="headline-sub">
        The offer says <strong>{fmtMoney(says)}</strong>. Here&rsquo;s what actually lands in your account.
      </div>
      <div className="headline-legend">
        <div className="leg">
          <div className="leg-bar"><span style={{ width: Math.max(0, Math.min(100, (Y1.afterTax / says) * 100)) + "%" }} /></div>
          <div className="leg-row">
            <span>Gross first-year comp</span><span className="leg-val">{fmtMoney(says)}</span>
          </div>
          <div className="leg-row muted">
            <span>− Federal, {stateCode || "state"} &amp; FICA (~{taxPct}%)</span>
            <span className="leg-val">−{fmtMoney(says - Y1.afterTax)}</span>
          </div>
          <div className="leg-row muted">
            <span>− {cityName} rent baseline ({fmtMoney(Y1.rentMonthly)}/mo × 12)</span>
            <span className="leg-val">−{fmtMoney(Y1.rentAnnual)}</span>
          </div>
          <div className="leg-row total">
            <span>What actually lands</span>
            <span className="leg-val">{fmtMoney(Y1.takeHome)}</span>
          </div>
        </div>
        <ExplainToggle label="How did we calculate this?">
          <p>
            We take your <JargonTerm term="gross">gross</JargonTerm> first-year comp — base + sign-on + the year-one
            slice of your RSU grant + your bonus target — and subtract realistic tax withholding for a single filer
            in {stateCode || "your state"} (federal ~{Math.round(num(BRIEF.location && BRIEF.location.fedEffectiveRate, 0.22) * 100)}% effective,
            {" "}{stateRate > 0 ? "state ~" + Math.round(stateRate * 100) + "%" : "no state income tax"}, FICA 7.65%).
          </p>
          <p>
            Then we subtract <strong>{fmtMoney(Y1.rentMonthly)}/month</strong> for rent — a reasonable baseline for
            a modest 1-bedroom in {cityName}. Everything left is your to-spend money: groceries, travel, savings,
            loan payments, the works.
          </p>
          <p className="fine">
            These are AI-generated estimates, not tax advice. Your actual number depends on 401(k), health premiums,
            bonuses paid, and where you actually live.
          </p>
        </ExplainToggle>
      </div>
    </section>
  );
}

// Best-effort "City" from a "City, ST" location string.
function locationCity(loc) {
  if (!loc || typeof loc !== "string") return "your city";
  return loc.split(",")[0].trim() || "your city";
}

function BreakdownCards() {
  const items = [
    {
      key: "base",
      label: "Base salary",
      gross: OFFER.base,
      net: Y1.baseNet,
      suffix: "/yr",
      note: <>Paid twice a month. The only piece that&rsquo;s <strong>actually guaranteed</strong> &mdash; everything else has strings attached.</>,
      tone: "steady",
    },
    {
      key: "signon",
      label: "Sign-on bonus",
      gross: OFFER.signOn,
      net: Y1.signOnNet,
      suffix: "",
      note: <>You keep this only if you stay <strong>12+ months</strong>. Leaving early triggers the{" "}
        <JargonTerm term="clawback">clawback</JargonTerm> &mdash; you pay it back.</>,
      tone: "conditional",
    },
    {
      key: "rsu",
      label: "RSUs (year 1)",
      gross: OFFER.rsuTotal / OFFER.rsuYears,
      net: Y1.rsuNet,
      suffix: "",
      note: <>25% of a <strong>{fmtMoney(OFFER.rsuTotal)}</strong>{" "}
        <JargonTerm term="RSU">RSU</JargonTerm> grant, vesting at the 1-year{" "}
        <JargonTerm term="cliff">cliff</JargonTerm>. Value floats with the stock.</>,
      tone: "variable",
    },
  ];

  return (
    <section className="breakdown">
      <div className="sec-hd">
        <h2>The three pieces</h2>
        <p>Your offer isn&rsquo;t one number &mdash; it&rsquo;s three different kinds of money, with very different rules.</p>
      </div>
      <div className="break-grid">
        {items.map((it) => (
          <div key={it.key} className={"break-card tone-" + it.tone}>
            <div className="break-label">
              <span>{it.label}</span>
              <span className={"break-tag tag-" + it.tone}>
                {it.tone === "steady" && "Guaranteed"}
                {it.tone === "conditional" && "Conditional"}
                {it.tone === "variable" && "Variable"}
              </span>
            </div>
            <div className="break-gross">{fmtMoney(it.gross)}{it.suffix}</div>
            <div className="break-net-row">
              <span className="break-net">≈ {fmtMoney(it.net)}</span>
              <span className="break-net-lbl">after tax</span>
            </div>
            <div className="break-note">{it.note}</div>
          </div>
        ))}
      </div>
    </section>
  );
}

function EquityCard({ onOpen }) {
  const isPrivate = BRIEF.isPublic === false || !BRIEF.ticker;

  return (
    <section className="card card-equity">
      <div className="card-hd">
        <div>
          <div className="card-eyebrow">Equity reality check <AIBadge /></div>
          <h3>Your RSU value depends on {isPrivate ? "a private valuation." : "this stock."}</h3>
        </div>
      </div>
      {isPrivate ? (
        <div className="equity-private">
          <p>{BRIEF.rsuNote || (
            <>The <strong>{fmtMoney(OFFER.rsuTotal)}</strong> RSU figure is based on a private
            valuation (typically a 409A). There is no public market, so this number is highly
            uncertain &mdash; you can&rsquo;t sell the shares until a liquidity event (IPO or
            acquisition) that may never happen, or happen at a very different price.</>
          )}</p>
        </div>
      ) : (
        <StockChart ticker={BRIEF.ticker} />
      )}
      <p className="card-body">
        {BRIEF.stockNarrative && !isPrivate && <><em>{BRIEF.stockNarrative}</em><br/><br/></>}
        <JargonTerm term="RSUs">RSUs</JargonTerm> are taxed at <JargonTerm term="vest">vest</JargonTerm> as{" "}
        <JargonTerm term="ordinary income">ordinary income</JargonTerm> &mdash; meaning when shares land in
        your account, the IRS treats them exactly like salary. The <strong>{fmtMoney(OFFER.rsuTotal)}</strong>{" "}
        figure on your offer is what {OFFER.company} says the grant is worth <em>today</em>. It is{" "}
        <strong>not</strong> what the grant will actually pay out.
      </p>
      <ExplainToggle label="Explain what this really means for me">
        <p>
          Say you&rsquo;re granted 2,000 shares at $15 each &mdash; that&rsquo;s the $30k&rsquo;s worth that lands
          at your 1-year cliff on paper. But when those shares actually vest, they&rsquo;re only worth whatever
          the stock is trading at <em>that day</em>.
        </p>
        <p>
          If the price doubles, great &mdash; your $30k becomes $60k. If it halves, your $30k becomes $15k and
          you still owe taxes on the value at vest. The {fmtMoney(OFFER.rsuTotal)} on your offer letter is a
          target, not a promise.
        </p>
      </ExplainToggle>
      <button className="card-link" onClick={onOpen}>
        See full equity analysis <span aria-hidden="true">→</span>
      </button>
    </section>
  );
}

function StabilityCard({ onOpen }) {
  const layoffs = BRIEF.layoffs || [];
  const hasLayoffs = layoffs.length > 0;

  // Build a one-line summary from the most recent rounds.
  const summary = hasLayoffs
    ? layoffs.slice(0, 2).map((e) => `${e.pct || "some"} in ${e.date}`).join(", then ")
    : null;

  if (!hasLayoffs) {
    return (
      <section className="card card-flag card-flag-ok">
        <div className="flag-body">
          <div className="card-eyebrow">Stability check <AIBadge /></div>
          <h3>No major layoffs found for {OFFER.company}.</h3>
          <p>
            We didn&rsquo;t surface well-known recent reductions — but absence of evidence isn&rsquo;t a
            guarantee. It&rsquo;s still worth asking about severance and equity acceleration before you sign.
          </p>
        </div>
      </section>
    );
  }

  return (
    <section className="card card-flag" onClick={onOpen} role="button" tabIndex={0}
             onKeyDown={(e) => (e.key === "Enter" || e.key === " ") && onOpen()}>
      <div className="flag-icon" aria-hidden="true">
        <svg viewBox="0 0 24 24" width="18" height="18">
          <path d="M12 3 L22 20 H2 Z" fill="none" stroke="currentColor" strokeWidth="1.6"
                strokeLinejoin="round" />
          <line x1="12" y1="10" x2="12" y2="15" stroke="currentColor" strokeWidth="1.6"
                strokeLinecap="round" />
          <circle cx="12" cy="17.5" r="0.9" fill="currentColor" />
        </svg>
      </div>
      <div className="flag-body">
        <div className="card-eyebrow">Stability flag <AIBadge /></div>
        <h3>{OFFER.company} cut staff {summary}.</h3>
        <p>
          Recent hires are often affected first. Factor this into your negotiation &mdash; sign-on cash is
          more secure than RSUs you haven&rsquo;t vested yet.
        </p>
        <span className="card-link-inline">See layoff history <span aria-hidden="true">→</span></span>
      </div>
    </section>
  );
}

const MISSING_ITEMS = [
  {
    key: "refresh",
    label: "Refresh grant policy",
    why: <>After your initial 4-year RSU grant vests, your equity drops to zero unless the company issues
      a <JargonTerm term="refresh">refresh grant</JargonTerm>. Many top companies refresh annually starting
      year 2 or 3. Ask: &ldquo;What&rsquo;s your typical refresh cadence and size for engineers at my level?&rdquo;</>,
  },
  {
    key: "acceleration",
    label: "Equity acceleration on termination",
    why: <>If the company lays you off, do your next-to-vest shares <JargonTerm term="equity acceleration">
      accelerate</JargonTerm>? Some companies offer 3–12 months of acceleration, especially in a severance
      package. Given the layoff history here, this is worth asking about directly.</>,
  },
  {
    key: "relocation",
    label: "Relocation package details",
    why: <>The offer mentions LA but says nothing about relo. Typical new-grad relo packages are $5k–$15k
      in cash + temporary housing. If you&rsquo;re moving across the country, ask for the specifics in
      writing &mdash; and whether any of it has its own clawback.</>,
  },
  {
    key: "severance",
    label: "Severance policy",
    why: <>What does severance look like if you&rsquo;re let go? Typical tech severance is 2–4 weeks of
      base per year worked, sometimes plus health coverage. A written severance policy is a real safety
      net &mdash; the absence of one is a risk you should price in.</>,
  },
];

function MissingCard() {
  const [openIdx, setOpenIdx] = useS(null);
  const items = (BRIEF.missingFlags && BRIEF.missingFlags.length)
    ? BRIEF.missingFlags.map((f, i) => ({ key: "flag-" + i, label: f.label, why: f.why }))
    : MISSING_ITEMS;
  const count = items.length;
  const countWord = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight"][count] || count;

  return (
    <section className="card card-missing">
      <div className="card-hd-col">
        <div className="card-eyebrow">Things your offer letter didn&rsquo;t mention <AIBadge /></div>
        <h3>{count === 1 ? "One thing" : `${cap(countWord)} things`} to ask about before you sign.</h3>
        <p className="card-body">These aren&rsquo;t red flags &mdash; they&rsquo;re <strong>standard things</strong> the
          offer letter is quiet about. Getting them in writing costs you nothing.</p>
      </div>
      <ul className="missing-list">
        {items.map((it, i) => {
          const open = openIdx === i;
          return (
            <li key={it.key} className={"missing-item" + (open ? " open" : "")}>
              <button className="missing-hd" onClick={() => setOpenIdx(open ? null : i)}
                      aria-expanded={open}>
                <span className="missing-check" aria-hidden="true" />
                <span className="missing-label">{it.label}</span>
                <span className="missing-caret" aria-hidden="true">{open ? "−" : "+"}</span>
              </button>
              {open && (
                <div className="missing-body">
                  <div className="missing-why">Why this matters</div>
                  <p>{it.why}</p>
                </div>
              )}
            </li>
          );
        })}
      </ul>
    </section>
  );
}

function cap(s) { return s ? s.charAt(0).toUpperCase() + s.slice(1) : s; }

function NegotiationCTA({ onOpen }) {
  return (
    <section className="cta" onClick={onOpen} role="button" tabIndex={0}
             onKeyDown={(e) => (e.key === "Enter" || e.key === " ") && onOpen()}>
      <div className="cta-eyebrow">Drafted for you</div>
      <div className="cta-grid">
        <div className="cta-copy">
          <h3>We wrote the negotiation email for you.</h3>
          <p>Personalized to your offer, the stability signals above, and the four open questions. Edit it,
             send it, or use it as a starting point.</p>
        </div>
        <div className="cta-preview">
          <div className="cta-preview-meta">
            <div><span className="meta-k">To</span> recruiter@{BRIEF.companyDomain || "company.com"}</div>
            <div><span className="meta-k">Subject</span> Following up on my offer — a few questions</div>
          </div>
          <div className="cta-preview-body">
            <p>Hi [Recruiter], thanks so much for the offer &mdash; I&rsquo;m genuinely excited about the team.
              Before I sign, I had a few quick questions I&rsquo;d love to clarify&hellip;</p>
            <div className="cta-preview-fade" />
          </div>
        </div>
      </div>
      <div className="cta-actions">
        <span className="cta-btn">Read the full draft <span aria-hidden="true">→</span></span>
        <span className="cta-sub">4 tailored questions · ready to send in under a minute</span>
      </div>
    </section>
  );
}

function BenefitsCard() {
  const benefits = BRIEF.benefits || [];
  if (!benefits.length) return null;

  const totalValue = benefits.reduce((s, b) => s + (typeof b.estAnnualValueUSD === "number" ? b.estAnnualValueUSD : 0), 0);

  return (
    <section className="card card-benefits">
      <div className="card-hd-col">
        <div className="card-eyebrow">Perks &amp; benefits <AIBadge /></div>
        <h3>The stuff that isn&rsquo;t in your paycheck.</h3>
        <p className="card-body">
          Free meals, shuttles, ride credits, 401(k) match &mdash; these have real dollar value even though
          they never hit your bank account.
          {totalValue > 0 && <> Roughly <strong>{fmtMoney(totalValue)}/yr</strong> of estimated value here.</>}
        </p>
      </div>
      <div className="benefits-grid">
        {benefits.map((b, i) => (
          <div key={i} className="benefit-item">
            <div className="benefit-top">
              <span className="benefit-name">{b.name}</span>
              <span className={"benefit-conf conf-" + (b.confidence || "low")}>{b.confidence || "low"}</span>
            </div>
            <div className="benefit-desc">{b.description}</div>
            {typeof b.estAnnualValueUSD === "number" && (
              <div className="benefit-val">≈ {fmtMoney(b.estAnnualValueUSD)}/yr</div>
            )}
          </div>
        ))}
      </div>
    </section>
  );
}

function LocationCard() {
  const loc = BRIEF.location || {};
  const demo = loc.demographics || {};
  if (!demo.summary && !(demo.notableGroups && demo.notableGroups.length) && !loc.costOfLivingIndex) return null;

  const coli = loc.costOfLivingIndex;
  const coliLabel = typeof coli === "number"
    ? (coli > 100 ? `${Math.round(coli - 100)}% above` : `${Math.round(100 - coli)}% below`) + " US average"
    : null;

  return (
    <section className="card card-location">
      <div className="card-hd-col">
        <div className="card-eyebrow">Where you&rsquo;d live <AIBadge /></div>
        <h3>{loc.city || locationCity(OFFER.location)}{loc.state ? ", " + loc.state : ""}</h3>
      </div>
      <div className="location-grid">
        <div className="location-stats">
          {typeof loc.monthlyRent1br === "number" && (
            <div className="location-stat">
              <div className="location-stat-v">{fmtMoney(loc.monthlyRent1br)}</div>
              <div className="location-stat-l">est. 1BR rent / mo</div>
            </div>
          )}
          {coliLabel && (
            <div className="location-stat">
              <div className="location-stat-v">{coli}</div>
              <div className="location-stat-l">cost of living<br/>({coliLabel})</div>
            </div>
          )}
        </div>
        <div className="location-demo">
          {demo.summary && <p>{demo.summary}</p>}
          {demo.notableGroups && demo.notableGroups.length > 0 && (
            <div className="location-tags">
              {demo.notableGroups.map((g, i) => <span key={i} className="location-tag">{g}</span>)}
            </div>
          )}
          {demo.notes && <p className="fine">{demo.notes}</p>}
        </div>
      </div>
    </section>
  );
}

function CaveatsLine() {
  if (!BRIEF.caveats) return null;
  return (
    <div className="caveats-line">
      <span className="caveats-icon" aria-hidden="true">ⓘ</span>
      <span>{BRIEF.caveats}</span>
    </div>
  );
}

function CompareCTA({ onOpen }) {
  return (
    <section className="cta cta-compare" onClick={onOpen} role="button" tabIndex={0}
             onKeyDown={(e) => (e.key === "Enter" || e.key === " ") && onOpen()}>
      <div className="cta-eyebrow">Have more than one offer?</div>
      <div className="cta-grid">
        <div className="cta-copy">
          <h3>Compare this offer against another.</h3>
          <p>Paste a second offer and see them side by side &mdash; real take-home, cost-of-living-adjusted,
             perks, and stability, not just the headline number.</p>
        </div>
      </div>
      <div className="cta-actions">
        <span className="cta-btn">Compare offers <span aria-hidden="true">→</span></span>
      </div>
    </section>
  );
}

// Metrics for one offer/brief pair, used by the compare table.
function offerMetrics(offer, brief) {
  const th = computeTakeHome(offer, brief);
  const perksValue = (brief.benefits || []).reduce(
    (s, b) => s + (typeof b.estAnnualValueUSD === "number" ? b.estAnnualValueUSD : 0), 0);
  const coli = brief.location && typeof brief.location.costOfLivingIndex === "number"
    ? brief.location.costOfLivingIndex : 100;
  return {
    location: offer.location,
    grossY1: th.gross,
    takeHome: th.takeHome,
    realTakeHome: Math.round(th.takeHome / (coli / 100)), // cost-of-living adjusted
    rsuTotal: offer.rsuTotal,
    perksValue,
    layoffRounds: (brief.layoffs || []).length,
    coli,
  };
}

function CompareScreen({ onBack }) {
  const [text, setText] = useS("");
  const [loading, setLoading] = useS(false);
  const [stage, setStage] = useS(null);
  const [error, setError] = useS(null);
  const [offerB, setOfferB] = useS(null);
  const [briefB, setBriefB] = useS(null);

  const decode = async (offerText) => {
    if (!offerText.trim() || loading) return;
    setLoading(true); setError(null);
    try {
      setStage("parsing");
      const r = await fetch("/api/parse-offer", {
        method: "POST", headers: { "content-type": "application/json" },
        body: JSON.stringify({ offerText }),
      });
      const p = await r.json();
      if (!r.ok) throw new Error(p.error || "Failed to parse offer");
      const parsed = p.offer;
      const ob = {
        company: parsed.company || "Offer B",
        role: parsed.role || OFFER.role,
        location: parsed.location || "—",
        base: parsed.baseSalary ?? 0,
        signOn: parsed.signOnBonus ?? 0,
        rsuTotal: parsed.rsuTotal ?? 0,
        rsuYears: parsed.rsuVestingYears ?? 4,
        bonusPct: parsed.annualBonusPercent ?? 0,
      };
      setStage("brief");
      let bb = { location: {}, benefits: [], layoffs: [], isPublic: true };
      try {
        const br = await fetch("/api/offer-brief", {
          method: "POST", headers: { "content-type": "application/json" },
          body: JSON.stringify({ offer: ob }),
        });
        const bp = await br.json();
        if (br.ok && bp.brief) bb = bp.brief;
      } catch (e) { console.warn("brief B failed", e); }
      setOfferB(ob);
      setBriefB(bb);
    } catch (e) {
      setError(e && e.message ? e.message : String(e));
    } finally {
      setLoading(false); setStage(null);
    }
  };

  const handleFile = async (e) => {
    const file = e.target.files && e.target.files[0];
    if (!file) return;
    try {
      const isPdf = file.type === "application/pdf" || file.name.toLowerCase().endsWith(".pdf");
      const raw = isPdf ? await extractPdfText(file) : await file.text();
      setText(raw);
      if (raw) decode(raw);
    } catch (err) {
      setError("Couldn't read that file: " + (err && err.message ? err.message : String(err)));
    }
  };

  const a = offerMetrics(OFFER, BRIEF);
  const b = offerB ? offerMetrics(offerB, briefB) : null;

  const rows = [
    { label: "Location", a: a.location, b: b && b.location, fmt: (v) => v },
    { label: "Gross year-1 comp", a: a.grossY1, b: b && b.grossY1, fmt: fmtMoney, hi: "max" },
    { label: "Take-home (after tax + rent)", a: a.takeHome, b: b && b.takeHome, fmt: fmtMoney, hi: "max" },
    { label: "Cost-of-living adjusted", a: a.realTakeHome, b: b && b.realTakeHome, fmt: fmtMoney, hi: "max" },
    { label: "RSU grant (4-yr)", a: a.rsuTotal, b: b && b.rsuTotal, fmt: fmtMoney, hi: "max" },
    { label: "Perks value / yr", a: a.perksValue, b: b && b.perksValue, fmt: fmtMoney, hi: "max" },
    { label: "Layoff rounds (recent)", a: a.layoffRounds, b: b && b.layoffRounds, fmt: (v) => v, hi: "min" },
  ];

  return (
    <ScreenShell
      eyebrow="Compare offers"
      title="Two offers, side by side."
      lede="The headline number rarely wins. Compare what actually lands in your account, adjusted for where you'd live."
      onBack={onBack}
    >
      {!offerB && (
        <section className="offer-input">
          <label className="offer-input-label">Paste your second offer letter</label>
          <textarea className="offer-input-textarea" value={text}
            onChange={(e) => setText(e.target.value)} rows={6} disabled={loading}
            placeholder="Paste the full text of the other offer, or upload a PDF…" />
          <div className="offer-input-row">
            <button className="offer-input-btn" onClick={() => decode(text)} disabled={loading || !text.trim()}>
              {loading ? <><span className="offer-input-spinner" aria-hidden="true" />
                {stage === "brief" ? "Researching…" : "Reading…"}</> : "Compare"}
            </button>
            <label className="offer-input-upload">
              <input type="file" accept="application/pdf,.pdf,.txt" onChange={handleFile} disabled={loading} hidden />
              <span>⬆ Upload PDF</span>
            </label>
            {error && <div className="offer-input-error">⚠ {error}</div>}
          </div>
        </section>
      )}

      {b && (
        <section className="eq-section">
          <div className="cmp-table">
            <div className="cmp-row cmp-head">
              <div className="cmp-metric"></div>
              <div className="cmp-cell">{OFFER.company}</div>
              <div className="cmp-cell">{offerB.company}</div>
            </div>
            {rows.map((row, i) => {
              const aWins = row.hi && typeof row.a === "number" && typeof row.b === "number" &&
                (row.hi === "max" ? row.a > row.b : row.a < row.b);
              const bWins = row.hi && typeof row.a === "number" && typeof row.b === "number" &&
                (row.hi === "max" ? row.b > row.a : row.b < row.a);
              return (
                <div key={i} className="cmp-row">
                  <div className="cmp-metric">{row.label}</div>
                  <div className={"cmp-cell" + (aWins ? " cmp-win" : "")}>{row.fmt(row.a)}</div>
                  <div className={"cmp-cell" + (bWins ? " cmp-win" : "")}>{row.fmt(row.b)}</div>
                </div>
              );
            })}
          </div>
          <p className="fine" style={{ marginTop: 16 }}>
            Highlighted cells are the stronger value on each row. &ldquo;Cost-of-living adjusted&rdquo; divides
            take-home by the local cost-of-living index &mdash; $1 goes further in some cities than others.
            All figures are AI-generated estimates.
          </p>
          <button className="offer-input-btn" style={{ marginTop: 16 }}
                  onClick={() => { setOfferB(null); setBriefB(null); setText(""); }}>
            Compare a different offer
          </button>
        </section>
      )}
    </ScreenShell>
  );
}

function Footer() {
  return (
    <footer className="site-ft">
      <div className="site-ft-inner">
        <BrandMark size={14} />
        <div className="site-ft-copy">
          Numbers and company details here are AI-generated estimates, not tax or legal advice. We don&rsquo;t store your offer letter. Verify anything important before relying on it, and take contract language to a lawyer.
        </div>
      </div>
    </footer>
  );
}

// ── App ─────────────────────────────────────────────────────────────────────

const TWEAK_DEFAULTS = /*EDITMODE-BEGIN*/{
  "accent": "forest",
  "density": "regular",
  "headlineScale": "large",
  "dark": false,
  "learn": false,
  "showWelcome": true
}/*EDITMODE-END*/;

const ACCENTS = {
  forest: { accent: "oklch(0.40 0.055 155)", accentSoft: "oklch(0.92 0.03 155)", accentInk: "oklch(0.28 0.05 155)" },
  indigo: { accent: "oklch(0.44 0.09 265)", accentSoft: "oklch(0.93 0.03 265)", accentInk: "oklch(0.32 0.08 265)" },
  clay:   { accent: "oklch(0.50 0.08 50)",  accentSoft: "oklch(0.94 0.03 60)",  accentInk: "oklch(0.36 0.07 50)"  },
  slate:  { accent: "oklch(0.30 0.01 240)", accentSoft: "oklch(0.93 0.005 240)", accentInk: "oklch(0.22 0.01 240)" },
};

function App() {
  const [t, setT] = useTweaks(TWEAK_DEFAULTS);
  const [screen, setScreen] = useS("dashboard"); // dashboard | equity | layoff | negotiation
  const [offerVersion, setOfferVersion] = useS(0); // bump to force dashboard re-render after parseOffer mutates OFFER/Y1

  const acc = ACCENTS[t.accent] || ACCENTS.forest;

  React.useEffect(() => {
    const r = document.documentElement;
    r.style.setProperty("--accent", acc.accent);
    r.style.setProperty("--accent-soft", acc.accentSoft);
    r.style.setProperty("--accent-ink", acc.accentInk);
    r.dataset.density = t.density;
    r.dataset.headline = t.headlineScale;
    r.dataset.mode = t.dark ? "dark" : "light";
    r.dataset.learn = t.learn ? "on" : "off";
  }, [t, acc]);

  // Scroll to top on screen change
  React.useEffect(() => {
    window.scrollTo({ top: 0, behavior: "instant" });
  }, [screen]);

  const goBack = () => setScreen("dashboard");

  return (
    <>
      {t.showWelcome && screen === "dashboard" && (
        <WelcomeBanner onClose={() => setT("showWelcome", false)} />
      )}
      <Header learn={t.learn} onLearn={(v) => setT("learn", v)} />
      <main className="page" key={screen}>
        {screen === "dashboard" && (
          <>
            <OfferInput onDecoded={() => setOfferVersion((v) => v + 1)} />
            <div key={offerVersion}>
              <MetaStrip />
              <Headline />
              <BreakdownCards />
              <EquityCard onOpen={() => setScreen("equity")} />
              <StabilityCard onOpen={() => setScreen("layoff")} />
              <BenefitsCard />
              <LocationCard />
              <MissingCard />
              <NegotiationCTA onOpen={() => setScreen("negotiation")} />
              <CompareCTA onOpen={() => setScreen("compare")} />
              <CaveatsLine />
            </div>
          </>
        )}
        {screen === "equity" && <EquityScreen onBack={goBack} />}
        {screen === "layoff" && <LayoffScreen onBack={goBack} />}
        {screen === "negotiation" && <NegotiationScreen onBack={goBack} />}
        {screen === "compare" && <CompareScreen onBack={goBack} />}
      </main>
      <Footer />

      <TweaksPanel title="Tweaks">
        <TweakSection label="Palette" />
        <TweakRadio label="Accent" value={t.accent}
                    options={["forest", "indigo", "clay", "slate"]}
                    onChange={(v) => setT("accent", v)} />
        <TweakToggle label="Dark mode" value={t.dark} onChange={(v) => setT("dark", v)} />
        <TweakSection label="Layout" />
        <TweakRadio label="Density" value={t.density}
                    options={["compact", "regular", "airy"]}
                    onChange={(v) => setT("density", v)} />
        <TweakRadio label="Headline" value={t.headlineScale}
                    options={[{ value: "balanced", label: "Balanced" },
                              { value: "large", label: "Large" },
                              { value: "huge", label: "Huge" }]}
                    onChange={(v) => setT("headlineScale", v)} />
      </TweaksPanel>
    </>
  );
}

ReactDOM.createRoot(document.getElementById("root")).render(<App />);
